#!/usr/bin/python3

import sys
import os
import subprocess

def is_install_command():
    return len(sys.argv) == 2

def is_https_command():
    return len(sys.argv) == 5 and sys.argv[2] == "https"

def is_name_command():
    return len(sys.argv) == 5 and sys.argv[2] == "name"

def inform_bad_command():
    print("./install [ip] -> install wordpress")
    print("./install [ip] https [domain] [your-email] -> sets up https for [domain]")
    print("./install [ip] name [name] [your-email] -> sets the user and email to display")

def get_ip():
    return sys.argv[1]

def get_domain():
    return sys.argv[3]

def get_email():
    return sys.argv[4]

def create_host_file(ip):
    str = ""
    with open('default.hosts.ini', 'r') as default_hosts:
        str = default_hosts.read()
    file_location = ".hosts.ini"
    str = "%s\n%s" % (str, ip)
    with open(file_location, "w") as text_file:
        print(str, file=text_file)
    return file_location

def get_host_file():
    return create_host_file(get_ip())

def run_ansible(command):
    hosts_file = get_host_file()
    dir_path = os.path.dirname(os.path.realpath(__file__))
    config_path = os.path.join(dir_path, "ansible.cfg")
    environment = os.environ.copy()
    environment['ANSIBLE_CONFIG'] = config_path
    command = ["ansible-playbook", "-i", hosts_file, "-l", "wp"] + command
    return subprocess.run(command, env=environment)

def run_ansible_wp_install():
    return run_ansible(["tasks/wp_install.yml"])

def run_ansible_https_setup():
    domain = get_domain()
    email = get_email()
    return run_ansible(["tasks/https_setup.yml", "--extra-vars", 
                        f"domain={domain} email={email}"])

def run_ansible_set_user():
    user = get_domain()
    email = get_email()
    return run_ansible(["tasks/wordpress_set_user.yml", "--extra-vars", 
                        f"user={user} email={email}"])



def install():
    run_ansible_wp_install()

def https():
    run_ansible_https_setup()

def name():
    run_ansible_set_user()

def main():
    if is_install_command():
        return install()
    elif is_https_command():
        return https()
    elif is_name_command():
        return name()
    else:
        return inform_bad_command()

main()