#!/usr/bin/python3

import sys
import os
import subprocess

def get_ip():
    return sys.argv[1]

def create_host_file(ip):
    str = ""
    with open('default.hosts.ini', 'r') as default_hosts:
        str = default_hosts.read()
    file_location = ".hosts.ini"
    str = "%s\n%s" % (str, ip)
    with open(file_location, "w") as text_file:
        print(str, file=text_file)
    return file_location

def run_ansible(hosts_file):
    dir_path = os.path.dirname(os.path.realpath(__file__))
    config_path = os.path.join(dir_path, "ansible.cfg")
    environment = os.environ.copy()
    environment['ANSIBLE_CONFIG'] = config_path
    os.environ['ANSIBLE_CONFIG'] = config_path
    command = ["ansible-playbook", "-i", hosts_file, "-l", "wp", "tasks/wp.yml"]
    subprocess.run(command, env=environment)

def main():
    ip = get_ip()
    host_file = create_host_file(ip)
    run_ansible(host_file)

main()