- name: "generate password in file /root/passwords/{{file}} with {{length}}"
  block:
    - name: "check if {{ name }} is already generated"
      stat:
        path: "/root/passwords/{{ file }}"
      register: file_generated
    - name: "starting to generate /root/passwords/{{ name }}"
      when: file_generated.stat.exists == False
      block:
        - name: ensuring directory /root/passwords/
          file:
            path: /root/passwords/
            state: directory
        - name: "generating /root/passwords/{{ name }}"
          shell: pwgen -s {{length}} 1 > /root/passwords/{{file}}