- name: install basic packages
  block:
    - name: php7 libs
      apt:
        pkg:
          - apache2
          - php7.2
          - php7.2-curl
          - php7.2-gd
          - php7.2-json
          - php7.2-imap
          - php7.2-mysql
          - php7.2-soap
          - php7.2-xmlrpc
          - php7.2-xml
          - php7.2-zip
          - php7.2-mbstring
          - php-xdebug
    - name: install utils
      apt:
        pkg:
          - vim
          - curl
          - zip
          - unzip
          - sendmail
          - openssl
          - ca-certificates
          - htop
          - git
          - python3

- name: install mysql
  block:
    - name: Check if mysql is installed
      stat: path=/usr/bin/mysql
      register: mysql_stat
    - when: mysql_stat.stat.exists == False
      block:
        - name: install repo configuration
          apt: deb=https://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb
        - name: install server and client
          apt:
            update_cache: yes
            pkg:
              - mysql-client=8.0.15-1ubuntu18.10
              - mysql-server=8.0.15-1ubuntu18.10

- name: install letsencrypt
  block:
    - name: Check if cert bot exists
      stat:
        path: /usr/local/bin/certbot-auto
      register: certbot_stat
    - name: install certbot-auto
      when: certbot_stat.stat.exists == False
      block:
        - name: enable apt-get autoaccept for future bootstraping
          copy:
            src: ../files/lamp/apt.conf.d/90forceyes
            dest: /etc/apt/apt.conf.d/90forceyes
        - name: download https://dl.eff.org/certbot-auto
          get_url:
            url: https://dl.eff.org/certbot-auto
            dest: /usr/local/bin/certbot-auto
            mode: 0555
    - name: install some certbot required packages
      apt:
        pkg:
          - python
          - python-dev
          - gcc
          - libssl-dev
          - openssl
          - libffi-dev
          - ca-certificates
    - name: run certbot one time to check if its ok
      command: certbot-auto -n -h
    - name: setup cerbot renewal cron
      cron:
        name: certbot-cron
        hour: 0
        minute: 5
        job: "python -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/local/bin/certbot-auto --quiet renew"

- name: init mysql db
  block:
    - name: restart mysql if it goes down
      cron:
          name: mysql-ensure-on-cron
          minute: "*/5"
          job: /usr/sbin/service mysql status > /dev/null || /usr/sbin/service mysql start
    - name: upload db init script
      copy: src=../files/lamp/init_db.sql dest=/tmp/init_db.sql
    - name: set user and password to init script
      include: replace_generated_password.yml file="/tmp/init_db.sql" replace="{{ item }}"
      with_items:
        - "DB_NAME"
        - "DB_USER"
        - "DB_PASSWORD"
    - name: exec init sql script
      shell: mysql < /tmp/init_db.sql
    - name: delete db init script
      file: path=/tmp/init_db.sql state=absent

- name: install pagespeed
  block:
    - name: check if pagespeed is installed
      stat: path=/usr/lib/apache2/modules/mod_pagespeed.so
      register: pagespeed_stat
    - when: pagespeed_stat.stat.exists == False 
      block:
        - name: download pagespeed package
          get_url:
            url: https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_amd64.deb
            dest: /tmp/mod-pagespeed-stable_current_amd64.deb
        - name: install page speed
          apt: deb=/tmp/mod-pagespeed-stable_current_amd64.deb
        - name: delete pagespeed deb download
          file: path=/tmp/mod-pagespeed-stable_current_amd64.deb state=absent

- name: apply custom configuration
  block:
     - name: delete any previous apache configuration
       file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
     - name: copy apache configuration
       copy: src=../files/lamp/sites-enabled/000-default.conf dest=/etc/apache2/sites-enabled/000-default.conf
     - name: copy apache ports configuration
       copy: src=../files/lamp/ports.conf dest=/etc/apache2/ports.conf
     - name: copy custom apache2.conf 
       copy: src=../files/lamp/apache2.conf dest=/etc/apache2/apache2.conf 
     - name: copy apache configuration
       copy: src=../files/lamp/mods-available/pagespeed.conf dest=/etc/apache2/mods-available/pagespeed.conf
     - name: copy custom php.ini
       copy: src=../files/lamp/php.ini dest=/etc/php/7.2/apache2/php.ini
     - name: copy apache2 log rotation config
       copy: src=../files/lamp/logrotate.d/apache2 dest=/etc/logrotate.d/apache2

- name: enable mods
  block:
    - name: enable deflate apache module
      shell: a2enmod deflate
    - name: enable filter apache module
      shell: a2enmod filter
    - name: enable rewrite apache module
      shell: a2enmod rewrite
    - name: enable ssl apache module
      shell: a2enmod ssl
    - name: enable substitute apache module
      shell: a2enmod substitute
    - name: Restart service apache
      service: name=apache2 state=restarted
    - name: Rotate apache2 logs
      shell: logrotate -vf /etc/logrotate.d/apache2