- name: install letsencrypt
  block:
    - name: Check if cert bot exists
      stat:
        path: /usr/local/bin/certbot-auto
      register: certbot_stat
    - name: install certbot-auto
      when: certbot_stat.stat.exists == False
      block:
        - name: enable apt-get autoaccept for future bootstraping
          copy:
            src: ../files/lamp/apt.conf.d/90forceyes
            dest: /etc/apt/apt.conf.d/90forceyes
        - name: download https://dl.eff.org/certbot-auto
          get_url:
            url: https://dl.eff.org/certbot-auto
            dest: /usr/local/bin/certbot-auto
            mode: 0555
    - name: install some certbot required packages
      apt:
        pkg:
          - python
          - python-dev
          - gcc
          - libssl-dev
          - openssl
          - libffi-dev
          - ca-certificates
    - name: run certbot one time to check if its ok
      command: certbot-auto -n -h
    - name: setup cerbot renewal cron
      cron:
        name: certbot-cron
        hour: 0,12
        job: "python -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/local/bin/certbot-auto renew"


- name: ask certificate for https://{{domain}} and send notifications to {{email}}
  shell: certbot-auto -n --agree-tos \
         -m {{email}} certonly \
         --webroot -w /var/www/default \
         -d {{domain}}

- name: setup apache configuration
  block:
    - name: ensure domain configuration file exists
      file:
        path: /etc/apache2/sites-enabled/001-domains.conf
        state: touch
    - name: "add apache configuration for https://{{domain}}"
      blockinfile:
        path: /etc/apache2/sites-enabled/001-domains.conf
        block: |
          <VirtualHost _default_:443>
              ServerName {{domain}}
              DocumentRoot /var/www/default
              SSLEngine on
              SSLCertificateFile      /etc/letsencrypt/live/{{domain}}/cert.pem
              SSLCertificateKeyFile   /etc/letsencrypt/live/{{domain}}/privkey.pem
              SSLCertificateChainFile /etc/letsencrypt/live/{{domain}}/chain.pem
          </VirtualHost>
    - name: Restart apache service
      service: name=apache2 state=restarted 