- name: "{{file}} replacing {{replace}} with password from /root/passwords/{{replace}}"
  block:
    - name: read password {{replace}}
      slurp: src="/root/passwords/{{replace}}"
      register: password_read
    - name: replacing into {{file}} the value of {{replace}}
      replace:
        dest: "{{file}}"
        regexp: "__REPLACE_WITH_{{replace}}__"
        replace: "{{(password_read.content | b64decode).replace('\n', '')}}"