---
- name: wp
  hosts: wp
  tasks:
    - name: setting user
      shell: sudo -u www-data wp --path='/var/www/default/' \
                  user update 1 \ 
                  --display_name={{ user }} \
                  --user_email={{ email }} \
                  --user_nicename={{ user }} \
                  --nickname={{ user }} \
                  --first_name={{ user }} \
                  --last_name={{ user }}\
    