CREATE DATABASE IF NOT EXISTS __REPLACE_WITH_DB_NAME__;
CREATE USER IF NOT EXISTS '__REPLACE_WITH_DB_USER__'@'localhost' IDENTIFIED WITH mysql_native_password BY  '__REPLACE_WITH_DB_PASSWORD__';
GRANT ALL PRIVILEGES ON __REPLACE_WITH_DB_NAME__.* TO '__REPLACE_WITH_DB_USER__'@'localhost';
FLUSH PRIVILEGES;